name: Test NodeJs Workflow
description: This is a simple GitHub Actions workflow to build a Node.js project.
on: push
jobs:
  test-nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
        working-directory: ./02 Starting Project
      - name: Run tests
        run: npm test
        working-directory: ./02 Starting Project